version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: person_db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: "person"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_users_service
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    environment:
      - R2DBC_URL=r2dbc:postgresql://host.docker.internal:5434/person
      - R2DBC_USER=postgres
      - R2DBC_PASSWORD=postgres
      - DB_URL=jdbc:postgresql://host.docker.internal:5434/person
      - DB_USER=postgres
      - DB_PASSWORD=postgres