spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USER}
    password: ${R2DBC_PASSWORD}
  flyway:
    url: ${DB_URL}
    locations: classpath:db/migration
    user: ${DB_USER}
    password: ${DB_PASSWORD}

api:
  keycloak:
    auth-server-url: http://localhost:8282
    admin:
      realm: master
      resource: admin-cli
      username: admin
      password: admin
    realm: users
    resource: my-gateway-user-service
    credentials:
      secret: jJm28F79oL8okiDkgaBJ5yqzQAxZtlaR
