server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/users

api:
  client:
    individual:
      url: http://localhost:8080/api/v1/individuals
      timeoutInSeconds: 10
