server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8282/realms/users-dev

api:
  client:
    individual:
      url: http://localhost:8080/api/v1/individuals
      timeoutInSeconds: 2
  keycloak:
    auth-server-url: http://localhost:8282
    admin:
      realm: master
      resource: admin-cli
      username: admin
      password: admin
    realm: users-dev
    resource: gateway-user-service
    credentials:
      secret: ERqCqXcXiIjCLtZz2Aq8uRDZSPaWwtjS

