server:
  port: 8081

spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL}

api:
  client:
    individual:
      url: ${INDIVIDUAL_CLIENT_URL}
      timeoutInSeconds: ${INDIVIDUAL_CLIENT_TIMEOUT}
  keycloak:
    auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
    admin:
      realm: ${KEYCLOAK_ADMIN_REALM}
      resource: ${KEYCLOAK_ADMIN_CLIENT}
      username: ${KEYCLOAK_ADMIN_USERNAME}
      password: ${KEYCLOAK_ADMIN_PASSWORD}
    realm: ${KEYCLOAK_REALM}
    resource: ${KEYCLOAK_CLIENT}
    credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET}

